"""Constantes BABIFIX : moyens de paiement (CI) et slugs d'icônes catégories (fichiers static)."""

from __future__ import annotations

# Slugs → fichiers static/category-icons/{slug}.svg (catalogue étendu prestations à domicile)
CATEGORY_ICON_SLUGS: tuple[tuple[str, str], ...] = (
    ('goutte', 'Plomberie & eau'),
    ('eclair', 'Électricité'),
    ('climatisation', 'Climatisation'),
    ('chauffage', 'Chauffage'),
    ('cle', 'Serrurerie'),
    ('fenetre', 'Vitrerie'),
    ('pinceau', 'Peinture'),
    ('carrelage', 'Carrelage & faïence'),
    ('menuiserie', 'Menuiserie & bois'),
    ('tondeuse', 'Jardinage'),
    ('elagage', 'Élagage & arbres'),
    ('balai', 'Ménage courant'),
    ('nettoyage', 'Nettoyage pro / profond'),
    ('demenagement', 'Déménagement'),
    ('escalier', 'Montage & escaliers'),
    ('marteau', 'Bricolage'),
    ('frigo', 'Électroménager'),
    ('ordinateur', 'Informatique'),
    ('domotique', 'Domotique & réseaux'),
    ('assistance', 'Assistance personnes'),
    ('enfant', 'Garde enfants'),
    ('animal', 'Animaux'),
    ('toilettage', 'Toilettage'),
    ('cours', 'Cours & soutien'),
    ('sport', 'Sport & coaching'),
    ('ciseaux', 'Coiffure & beauté'),
    ('massage', 'Massage & bien-être'),
    ('photo', 'Photo & vidéo'),
    ('musique', 'Son & musique'),
    ('voiture', 'Auto & mécanique'),
    ('lavage-auto', 'Lavage auto'),
    ('casserole', 'Cuisine'),
    ('telephone', 'Smartphone & tablette'),
    ('vitrage', 'Vitrage urgence'),
    ('desinfection', 'Désinfection & nuisibles'),
    ('piscine', 'Piscine & spa'),
    ('arrosage', 'Arrosage & irrigation'),
    ('maison', 'Conseil habitat'),
    ('inspection', 'Inspection & diagnostic'),
    ('securite', 'Sécurité & alarme'),
    ('outils', 'Outils pro'),
    ('multiservices', 'Multiservices'),
    ('toiture', 'Toiture & zinguerie'),
    ('maconnerie', 'Maçonnerie & béton'),
    ('isolation', 'Isolation thermique & phonique'),
    ('ravalement', 'Ravalement de façade'),
    ('sol-souple', 'Moquette & sols souples'),
    ('tapisserie-deco', 'Tapisserie & revêtements muraux'),
    ('metallier', 'Ferronnerie & garde-corps'),
    ('stores-volets', 'Stores & volets'),
    ('placo', 'Cloisons & placo'),
    ('etancheite', 'Étanchéité toiture-terrasse'),
    ('cloture', 'Clôtures & portails'),
    ('forage', 'Forage & pompes'),
    ('demoussage', 'Démoussage toiture'),
    ('taille-haies', 'Taille de haies'),
    ('engazonnement', 'Gazon & semis'),
    ('potager', 'Potager & permaculture'),
    ('bassin', 'Bassins & fontaines'),
    ('repassage', 'Repassage à domicile'),
    ('courses', 'Courses & livraison'),
    ('conciergerie', 'Conciergerie'),
    ('aide-quotidien', 'Aide à la vie quotidienne'),
    ('traiteur', 'Traiteur & réceptions'),
    ('animation', 'Animation & spectacle privé'),
    ('deco-fetes', 'Décoration d’événements'),
    ('antenne', 'Antenne TNT & satellite'),
    ('couture', 'Couture & retouches'),
    ('debarras', 'Débarras & encombrants'),
    ('montage-velo', 'Vélo & mobilité douce'),
    ('home-staging', 'Home staging'),
    ('rideaux', 'Rideaux & tringles'),
    ('vmc', 'VMC & extraction d’air'),
    ('luminaires', 'Luminaires & lustres'),
    ('pressing', 'Pressing & textile'),
    ('gaz-cuisson', 'Gaz & appareils de cuisson'),
    ('soudure', 'Soudure légère'),
)

# id technique → chemin relatif static, libellé affiché (exact)
PAYMENT_METHOD_STATIC: tuple[tuple[str, str, str], ...] = (
    ('ESPECES', 'payment-logos/especes.svg', 'Espèces'),
    ('ORANGE_MONEY', 'payment-logos/orange-money.png', 'Orange Money'),
    ('MTN_MOMO', 'payment-logos/mtn-momo.png', 'MTN Mobile Money'),
    ('WAVE', 'payment-logos/wave.png', 'Wave'),
    ('MOOV', 'payment-logos/moov-money.png', 'Moov Money'),
)
