org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=128m -XX:+UseSerialGC
org.gradle.daemon=false
org.gradle.parallel=false
android.useAndroidX=true
android.enableJetifier=true

systemProp.net.preferIPv4Stack=true
systemProp.java.net.preferIPv4Stack=true
systemProp.sun.net.inetaddr.ttl=0
