services:
  - type: web
    name: babifix-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --no-input &&
      python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: babifix-api.onrender.com
      - key: POSTGRES_DB
        fromDatabase:
          name: babifix-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: babifix-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: babifix-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: babifix-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: babifix-db
          property: port
      - key: REDIS_URL
        fromService:
          name: babifix-redis
          type: redis
          property: connectionString
      - key: GENIUSPAY_PUBLIC_KEY
        value: pk_live_RuhR13Fw4ETRmbjmONk2ZGBWeObzSet2
      - key: GENIUSPAY_SECRET_KEY
        sync: false
      - key: GENIUSPAY_WEBHOOK_URL
        value: https://babifix-api.onrender.com/api/paiements/geniuspay/webhook/
      - key: CORS_ALLOWED_ORIGINS
        value: https://babifix-api.onrender.com
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: kouayavana20@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: kouayavana20@gmail.com

databases:
  - name: babifix-db
    plan: free
    region: frankfurt

  - name: babifix-redis
    plan: free
    region: frankfurt
