# Generated by Django 5.2.10 on 2026-04-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_contact_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['ordre_affichage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, default='', max_length=200)),
                ('soustitre', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenu héros',
                'verbose_name_plural': 'Contenus héros',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('ville', models.CharField(blank=True, default='', max_length=120)),
                ('texte', models.TextField()),
                ('note', models.PositiveSmallIntegerField(default=5, help_text='Note sur 5')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('actif', models.BooleanField(default=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['ordre_affichage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitrineStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('valeur', models.CharField(help_text='Ex: 10,000+', max_length=50)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistique vitrine',
                'verbose_name_plural': 'Statistiques vitrine',
                'ordering': ['ordre_affichage'],
            },
        ),
    ]
