# Generated by Django 5.2.10 on 2026-03-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('services', models.PositiveIntegerField(default=0)),
                ('reservations', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.CharField(max_length=80)),
                ('reservations', models.PositiveIntegerField(default=0)),
                ('depense', models.CharField(default='0 FCFA', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('motif', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=120)),
                ('prestataire', models.CharField(max_length=120)),
                ('priorite', models.CharField(choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Basse', 'Basse')], default='Moyenne', max_length=10)),
                ('decision', models.CharField(choices=[('En cours', 'En cours'), ('Rembourser client', 'Rembourser client'), ('Liberer paiement', 'Liberer paiement'), ('Partage partiel', 'Partage partiel')], default='En cours', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.CharField(default='A l instant', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('client', models.CharField(max_length=120)),
                ('prestataire', models.CharField(max_length=120)),
                ('montant', models.CharField(max_length=40)),
                ('commission', models.CharField(max_length=40)),
                ('etat', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Litige', 'Litige')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('specialite', models.CharField(max_length=80)),
                ('ville', models.CharField(max_length=80)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Valide', 'Valide'), ('Suspendu', 'Suspendu')], default='En attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('client', models.CharField(max_length=120)),
                ('prestataire', models.CharField(max_length=120)),
                ('montant', models.CharField(max_length=40)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Confirmee', 'Confirmee'), ('Terminee', 'Terminee')], default='En attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.PositiveIntegerField(default=10)),
                ('auto_validation', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('mode_paiement', models.CharField(default='CinetPay + Carte', max_length=60)),
            ],
        ),
    ]
