# Generated by Django 5.2.10 on 2026-03-21 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_unified_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordre_affichage', 'nom']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='icone_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='ordre_affichage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_externe',
            field=models.CharField(blank=True, default='', help_text='CinetPay / autre', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='adminpanel.reservation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type_paiement',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('ESPECES', 'Especes'), ('CARTE', 'Carte')], default='ESPECES', max_length=24),
        ),
        migrations.AddField(
            model_name='payment',
            name='valide_par_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='provider',
            name='cni_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='provider',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='tarif_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cash_admin_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cash_client_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cash_flow_status',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('pending_prestataire', 'En attente prestataire'), ('pending_admin', 'En attente validation admin'), ('validated', 'Valide'), ('refused', 'Refuse')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cash_prestataire_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cash_refusal_motif',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_message',
            field=models.TextField(blank=True, default='', help_text='Message client lors de la réservation (UML)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_type',
            field=models.CharField(choices=[('ESPECES', 'Especes'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte'), ('AUTRE', 'Autre')], default='ESPECES', max_length=24),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmee', 'Confirmee'), ('En cours', 'En cours'), ('Terminee', 'Terminee'), ('Annulee', 'Annulee')], default='En attente', max_length=20),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babifix_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='adminpanel.provider')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='adminpanel.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
