# Generated by Django 5.2.10 on 2026-03-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_reservation_mobile_money_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='mode_paiement',
            field=models.CharField(default='Especes + Orange Money, MTN MoMo, Wave, Moov (CI)', max_length=120),
        ),
    ]
