# Generated by Django 5.2.10 on 2026-03-22 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_approved(apps, schema_editor):
    Provider = apps.get_model('adminpanel', 'Provider')
    Provider.objects.filter(statut='Valide').update(is_approved=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_devicetoken_token_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Catégorie métier (icône / filtre client)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='adminpanel.category'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Aligné sur statut Valide — visible apps client'),
        ),
        migrations.RunPython(forwards_approved, noop_reverse),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='actualites/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(db_index=True, default=False)),
                ('categorie_tag', models.CharField(choices=[('nouveau_prestataire', 'Nouveau prestataire'), ('paiement', 'Paiement / Mobile Money'), ('promo', 'Promotion'), ('maintenance', 'Maintenance'), ('general', 'Général')], default='general', max_length=40)),
                ('icone_key', models.CharField(blank=True, default='', help_text='Clé simple (ex. megaphone) pour UI', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
    ]
