# Generated by Django 5.2.10 on 2026-03-23 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_conversation_reservation_message_lu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', 'prestataire'], name='adminpanel__client__e2a7ca_idx'),
        ),
    ]
