# Generated by Django 5.2.10 on 2026-03-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_conversation_adminpanel__client__e2a7ca_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icone_slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Clé icône BABIFIX (fichier static/category-icons/{slug}.svg)', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_confirme_prestation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dispute_ouverte',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_client_note',
            field=models.TextField(blank=True, default='', help_text='Message optionnel du client au moment du paiement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prestation_terminee_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='preuve_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmee', 'Confirmee'), ('En cours', 'En cours'), ('En attente client', 'En attente client'), ('Terminee', 'Terminee'), ('Annulee', 'Annulee')], default='En attente', max_length=20),
        ),
    ]
