# Generated by Django 5.2.10 on 2026-03-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_workflow_category_payment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='photo_attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='category',
            name='icone_slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Slug → static/category-icons/{slug}.svg (SVG multicolore ; remplaçable par export IconScout sous licence, même nom de fichier).', max_length=64),
        ),
    ]
