# Generated by Django 5.2.10 on 2026-04-02 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_adminauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='adminpanel.reservation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='lu',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('reservation', 'Réservation'), ('message', 'Message'), ('validation', 'Validation compte'), ('broadcast', 'Annonce'), ('payment', 'Paiement'), ('dispute', 'Litige'), ('general', 'Général')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Référence liée (réservation, litige…)', max_length=60),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='None = notification admin globale', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='babifix_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provider',
            name='portfolio_photos',
            field=models.JSONField(blank=True, default=list, help_text='Liste de {photo, caption, added_at} — max 12 entrées'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verify_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='babifix_client_ratings_received', to=settings.AUTH_USER_MODEL)),
                ('prestataire_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babifix_client_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_rating', to='adminpanel.reservation')),
            ],
            options={
                'verbose_name': 'Évaluation client',
                'verbose_name_plural': 'Évaluations clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
