# Generated by Django 5.2.10 on 2026-04-03 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_prestataireunavailability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.PositiveSmallIntegerField(default=10, help_text='Taux de commission en pourcentage (ex: 10 = 10%)')),
                ('actif', models.BooleanField(default=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='adminpanel.category')),
            ],
            options={
                'verbose_name': 'Commission catégorie',
                'verbose_name_plural': 'Commissions catégories',
            },
        ),
    ]
