# Generated by Django 5.2.10 on 2026-04-17 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_prix_propose_cni_recto_verso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='depense',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dépense totale en FCFA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Maximum 5000 caractères', validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='commission',
            field=models.DecimalField(decimal_places=2, help_text='Commission en FCA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant en FCA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant de la réservation en FCA', max_digits=12),
        ),
    ]
