# Generated by Django 5.2.10 on 2026-04-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_alter_client_depense_alter_message_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='description_probleme',
            field=models.TextField(blank=True, default='', help_text='Description du problème par le client'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='disponibilites_client',
            field=models.CharField(blank=True, default='', help_text="Disponibilités du client: 'Matin, Après-midi, Lun-Mer'", max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Intervention urgente demandée par le client'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='motif_refus_demande',
            field=models.TextField(blank=True, default='', help_text='Motif de refus de la demande par le prestataire'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='photos_probleme',
            field=models.JSONField(blank=True, default=list, help_text='URLs des photos du problème'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmee', 'Confirmee'), ('En cours', 'En cours'), ('En attente client', 'En attente client'), ('Terminee', 'Terminee'), ('Annulee', 'Annulee'), ('DEMANDE_ENVOYEE', 'Demande envoyée'), ('DEVIS_EN_COURS', 'Devis en cours'), ('DEVIS_ENVOYE', 'Devis envoyé'), ('DEVIS_ACCEPTE', 'Devis accepté'), ('INTERVENTION_EN_COURS', 'Intervention en cours')], default='En attente', max_length=30),
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('diagnostic', models.TextField(help_text='Analyse du problème par le prestataire')),
                ('date_proposee', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_rate', models.IntegerField(default=10)),
                ('commission_montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note_prestataire', models.TextField(blank=True, default='')),
                ('validite_jours', models.IntegerField(default=7)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_crees', to='adminpanel.provider')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_set', to='adminpanel.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('FOURNITURE', 'Fourniture'), ('MAIN_OEUVRE', "Main d'œuvre"), ('DEPLACEMENT', 'Déplacement'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='adminpanel.devis')),
            ],
        ),
    ]
