# Generated by Django 5.2.10 on 2026-04-21 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_add_devis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='after_photos',
            field=models.JSONField(blank=True, default=list, help_text='Liste photos après intervention'),
        ),
        migrations.AddField(
            model_name='provider',
            name='before_photos',
            field=models.JSONField(blank=True, default=list, help_text='Liste photos avant intervention'),
        ),
        migrations.AddField(
            model_name='provider',
            name='certified_at',
            field=models.DateTimeField(blank=True, help_text='Date de certification Admin', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_certified',
            field=models.BooleanField(default=False, help_text="Badge 'Prestataire Certifié' — validation après review admin"),
        ),
        migrations.AddField(
            model_name='provider',
            name='selfie_url',
            field=models.CharField(blank=True, default='', help_text='Selfie avec CNI - validation identité', max_length=500),
        ),
        migrations.AddField(
            model_name='provider',
            name='video_intro_url',
            field=models.CharField(blank=True, default='', help_text='Vidéo intro 30-60s - filtre qualité', max_length=500),
        ),
        migrations.AlterField(
            model_name='devis',
            name='commission_rate',
            field=models.IntegerField(default=18, help_text='Commission plateforme (15-20% recommandé)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='commission',
            field=models.DecimalField(decimal_places=2, help_text='Commission en francs CFA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant en francs CFA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant de la réservation en francs CFA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmee', 'Confirmee'), ('En cours', 'En cours'), ('En attente client', 'En attente client'), ('Terminee', 'Terminee'), ('Annulee', 'Annulee'), ('DEMANDE_ENVOYEE', 'Demande envoyée'), ('DEVIS_EN_COURS', 'Devis en cours'), ('DEVIS_ENVOYE', 'Devis envoyé'), ('DEVIS_ACCEPTE', 'Devis accepté'), ('INTERVENTION_EN_COURS', 'Intervention en cours')], default='DEMANDE_ENVOYEE', max_length=30),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_nom', models.CharField(default='3 interventions', max_length=50)),
                ('pack_interventions', models.IntegerField(default=3)),
                ('interventions_utilisees', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
