# Generated by Django 5.2.10 on 2026-04-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_premium_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text="Clé d'idempotence pour éviter les doublons", max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_used_at',
            field=models.DateTimeField(blank=True, help_text="Date d'utilisation de la clé", null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date de suppression soft', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete - ne pas afficher si True'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date de suppression soft', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete - compte désactivé si True'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_externe',
            field=models.CharField(blank=True, default='', help_text=' Référence CinetPay ou autre externe', max_length=64),
        ),
        migrations.AlterField(
            model_name='payment',
            name='valide_par_admin',
            field=models.BooleanField(default=False, help_text='Validé par admin pour les espèces'),
        ),
    ]
