# Generated by Django 5.2.10 on 2026-04-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_security_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='appel_masque',
            field=models.BooleanField(default=False, help_text='Appel masqué activé via ZEGOCLOUD'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission BABIFIX 18% calculée automatiquement', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text="Clé d'idempotence pour les paiements", max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='numero_masque',
            field=models.CharField(blank=True, default='', help_text='Numéro masqué temporaire pour appel ZEGOCLOUD', max_length=20),
        ),
    ]
