# Generated by Django 5.2.10 on 2026-04-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_reservation_appel_masque_reservation_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='photos_apres',
            field=models.JSONField(blank=True, default=list, help_text='URLs des photos après intervention'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='photos_avant',
            field=models.JSONField(blank=True, default=list, help_text='URLs des photos avant intervention'),
        ),
    ]
