# Generated by Django 5.2.10 on 2026-04-25 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_add_photos_avant_apres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='provider',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Abonnement premium actif (bronze/silver/gold)'),
        ),
        migrations.AddField(
            model_name='provider',
            name='premium_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='premium_tier',
            field=models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Argent'), ('gold', 'Or')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommended_by',
            field=models.ForeignKey(blank=True, help_text='Parrain qui a invite cet utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_bonus_applied',
            field=models.BooleanField(default=False, help_text='Bonus premiere reservation applique'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Code de parrainage unique', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code_used',
            field=models.CharField(blank=True, default='', help_text="Code de parrainage utilise a l'inscription", max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_credits_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credits gagnes via parrainage', max_digits=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Aligne sur statut Valide — visible apps client'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_certified',
            field=models.BooleanField(default=False, help_text="Badge 'Prestataire Certifie' — validation apres review admin"),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete - prestataire supprime si True'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='appel_masque',
            field=models.BooleanField(default=False, help_text='Appel masquevia ZEGOCLOUD'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='numero_masque',
            field=models.CharField(blank=True, default='', help_text='Numero masque temporaire pour appel ZEGOCLOUD', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete - compte desactive si True'),
        ),
    ]
