# Generated by Django 5.2.10 on 2026-04-29 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0033_provider_kyc_auto_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='adminpanel__provide_8e2428_idx',
            old_name='wallet_tx_provider_idx',
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_cni_expiry',
            field=models.DateField(blank=True, help_text="Date d'expiration de la CNI", null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_cni_number',
            field=models.CharField(blank=True, default='', help_text='Numéro de la CNI', max_length=80),
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_cni_recto_url',
            field=models.TextField(blank=True, default='', help_text='URL recto CNI (base64 ou fichier)'),
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_cni_verso_url',
            field=models.TextField(blank=True, default='', help_text='URL verso CNI (base64 ou fichier)'),
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Motif de rejet du dossier KYC'),
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de validation/rejet par admin', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin qui a examiné le dossier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_selfie_url',
            field=models.TextField(blank=True, default='', help_text='URL selfie avec CNI'),
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Non soumis'), ('pending', 'En attente'), ('under_review', 'En examen'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de soumission du dossier KYC', null=True),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='wallet_phone',
            field=models.CharField(blank=True, default='', help_text='Numéro Mobile Money pour les retraits (MTN/Orange/Wave)', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
