# Generated by Django 5.2.10 on 2026-04-30 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0034_rename_wallet_tx_provider_idx_adminpanel__provide_8e2428_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', help_text='Ancien statut (vide si création)', max_length=40)),
                ('new_status', models.CharField(help_text='Nouveau statut', max_length=40)),
                ('comment', models.TextField(blank=True, default='', help_text='Commentaire optionnel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant effectué le changement', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='adminpanel.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', '-created_at'], name='adminpanel__reserva_943332_idx')],
            },
        ),
    ]
