# Generated by Django 5.2.10 on 2026-05-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_reservationstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='acompte_valide',
            field=models.BooleanField(default=False, help_text="L'acompte a été payé et bloqué, le prestataire peut commencer"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant restant dû à la fin de l'intervention", max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='montant_verse',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant déjà versé / bloqué (acompte)', max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='solde_valide',
            field=models.BooleanField(default=False, help_text='Le solde a été payé, le prestataire peut être rémunéré'),
        ),
    ]
