# Generated by Django 5.2.10 on 2026-05-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0036_reservation_acompte_valide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text="Soft delete: l'admin a masqué cette catégorie, elle ne s'affiche plus mais les anciennes données sont conservées."),
        ),
        migrations.AlterField(
            model_name='category',
            name='actif',
            field=models.BooleanField(default=True, help_text='Visible sur les apps (désactivable temporairement)'),
        ),
    ]
