# Generated by Django 5.2.10 on 2026-05-25 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_premium_tiers_realign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_externe',
            field=models.CharField(blank=True, default='', help_text=' Référence GeniusPay ou autre externe', max_length=64),
        ),
        migrations.CreateModel(
            name='ProAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200)),
                ('contact_nom', models.CharField(blank=True, default='', max_length=120)),
                ('contact_telephone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('formule', models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('commission_rate', models.PositiveSmallIntegerField(default=10, help_text='Commission B2B en % (Starter 10, Business 8, Enterprise négociée)')),
                ('sla_heures', models.PositiveSmallIntegerField(default=24, help_text="Délai d'intervention contractuel en heures")),
                ('abonnement_mensuel_fcfa', models.DecimalField(decimal_places=2, default=0, help_text='Abonnement mensuel récurrent (SaaS B2B)', max_digits=12)),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('jour_facturation', models.PositiveSmallIntegerField(default=1, help_text='Jour du mois où la facture groupée est émise (1-28)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='Compte de connexion du gestionnaire B2B', on_delete=django.db.models.deletion.CASCADE, related_name='babifix_pro_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='ProSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : Résidence Les Palmiers, Bât. A', max_length=200)),
                ('adresse', models.CharField(blank=True, default='', max_length=500)),
                ('commune', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_sur_site', models.CharField(blank=True, default='', max_length=120)),
                ('telephone_sur_site', models.CharField(blank=True, default='', max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pro_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='adminpanel.proaccount')),
            ],
            options={
                'ordering': ['pro_account', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='pro_site',
            field=models.ForeignKey(blank=True, help_text='Site B2B concerné (intervention déclarée par un compte pro)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='adminpanel.prosite'),
        ),
        migrations.CreateModel(
            name='ProInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=40, unique=True)),
                ('periode', models.CharField(help_text='Mois facturé, format AAAA-MM', max_length=7)),
                ('nombre_interventions', models.PositiveIntegerField(default=0)),
                ('montant_interventions_fcfa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('abonnement_fcfa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fcfa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée')], default='brouillon', max_length=20)),
                ('detail', models.JSONField(blank=True, default=list, help_text='Lignes : par site / intervention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pro_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='adminpanel.proaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('pro_account', 'periode')},
            },
        ),
    ]
