# Generated by Django 5.2.10 on 2026-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0039_add_reservation_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission BABIFIX calculée automatiquement', max_digits=12, null=True),
        ),
    ]
