# Generated by Django 5.2.10 on 2026-05-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0039_alter_payment_reference_externe_proaccount_prosite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fidelite_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fidelite_credit_fcfa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédit de réduction obtenu en convertissant des points de fidélité', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points_fidelite',
            field=models.PositiveIntegerField(default=0, help_text='Points de fidélité cumulés (1 point par tranche de 1 000 FCFA dépensée)'),
        ),
    ]
