# Generated by Django 5.2.10 on 2026-05-13 15:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0043_message_kind_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='marque',
            field=models.CharField(blank=True, default='', help_text='Marque/référence matériau (optionnel, vue Kanban)', max_length=80),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(blank=True, default='', help_text='Unité (u, m, m², m³, ml, kg, h, jour, forfait…) — affichage UI', max_length=16),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text="Quantité (peut être décimale : ex 2.5 m de tuyau, 1.5 h de main d'œuvre).", max_digits=10),
        ),
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('FOURNITURE', 'Fourniture'), ('MAIN_OEUVRE', "Main d'œuvre"), ('DEPLACEMENT', 'Déplacement'), ('AUTRE', 'Autre')], default='FOURNITURE', help_text="Section devis (Fourniture / Main d'œuvre / Déplacement / Autre)", max_length=20)),
                ('nom', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('unite', models.CharField(blank=True, default='u', help_text='u, m, m², m³, ml, kg, h, jour, forfait…', max_length=16)),
                ('prix_unitaire_indicatif', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Prix indicatif (XOF). Le prestataire peut surcharger.', max_digits=10)),
                ('marque', models.CharField(blank=True, default='', max_length=80)),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_items', to='adminpanel.category')),
            ],
            options={
                'ordering': ['category', 'type_ligne', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='catalogue_item',
            field=models.ForeignKey(blank=True, help_text='Référence du catalogue catégorie si choisi via le catalogue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_devis', to='adminpanel.catalogueitem'),
        ),
        migrations.AddIndex(
            model_name='catalogueitem',
            index=models.Index(fields=['category', 'type_ligne', 'actif'], name='adminpanel__categor_6f482b_idx'),
        ),
    ]
