# Generated by Django 5.2.10 on 2026-05-13 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0044_catalogue_items_lignes_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('VOICE', 'Audio'), ('VIDEO', 'Vidéo')], default='VOICE', max_length=8)),
                ('status', models.CharField(choices=[('RINGING', 'Sonne'), ('ANSWERED', 'Décroché'), ('REJECTED', 'Refusé'), ('MISSED', 'Manqué'), ('ENDED', 'Terminé'), ('CANCELLED', "Annulé par l'appelant")], db_index=True, default='RINGING', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_initiated', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='adminpanel.reservation')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['caller', '-started_at'], name='adminpanel__caller__ff9961_idx'), models.Index(fields=['callee', '-started_at'], name='adminpanel__callee__c99209_idx'), models.Index(fields=['reservation', '-started_at'], name='adminpanel__reserva_548efa_idx')],
            },
        ),
    ]
