# Generated by Django 5.2.10 on 2026-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0045_call_signaling'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_journal_note',
            field=models.TextField(blank=True, default='', help_text="Commentaire libre du client à la fin de l'intervention (ressenti, détail des travaux, qualité…)."),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_journal_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_photos_apres',
            field=models.JSONField(blank=True, default=list, help_text='Photos après prises par le client (témoignage, facultatif)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_photos_avant',
            field=models.JSONField(blank=True, default=list, help_text='Photos avant prises par le client (témoignage, facultatif)'),
        ),
    ]
