# Generated by Django 5.2.10 on 2026-05-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0046_client_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrevenue',
            name='refunded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_by',
            field=models.CharField(blank=True, default='', help_text='CLIENT | PRESTATAIRE | ADMIN', max_length=16),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_motif',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_stage',
            field=models.CharField(blank=True, default='', help_text='before_devis | after_devis | after_accept | after_start', max_length=24),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_owed_fcfa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant que la plateforme doit rembourser au client (en attente admin)', max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_paid_at',
            field=models.DateTimeField(blank=True, help_text="Set par l'admin une fois le remboursement effectivement viré", null=True),
        ),
    ]
