# Generated by Django 5.2.10 on 2026-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0047_cancellation_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Telephone verifie via OTP Firebase'),
        ),
    ]
