# Generated by Django 5.2.10 on 2026-05-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0048_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='has_used_premium_trial',
            field=models.BooleanField(default=False, help_text="True dès qu'un essai gratuit 7j a été consommé (à vie)."),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_premium_annual',
            field=models.BooleanField(default=False, help_text="Abonnement annuel (vs mensuel). Verrouillé jusqu'à premium_until."),
        ),
        migrations.AlterField(
            model_name='provider',
            name='premium_tier',
            field=models.CharField(blank=True, choices=[('silver', 'Argent'), ('gold', 'Or')], default='', max_length=20),
        ),
    ]
