# Generated by Django 5.2.10 on 2026-05-18 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0049_premium_tier_trial_annual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='categorie',
            field=models.CharField(choices=[('travail_non_fait', 'Travail non réalisé'), ('travail_bacle', 'Travail bâclé / mal fait'), ('presta_absent', 'Prestataire absent / pas venu'), ('retard', 'Retard important'), ('prix_non_conforme', 'Prix non conforme au devis'), ('degats', 'Dégâts causés'), ('comportement', 'Comportement inapproprié'), ('autre', 'Autre')], db_index=True, default='autre', max_length=32),
        ),
        migrations.AddField(
            model_name='dispute',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='decision_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='photos_client',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dispute',
            name='photos_prestataire',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dispute',
            name='prestataire_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='prestataire_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='motif',
            field=models.CharField(max_length=500),
        ),
    ]
