# Generated by Django 5.2.10 on 2026-05-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0050_dispute_categorie_photos_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de versement'), ('success', 'Réussi'), ('failed', 'Échoué')], default='success', max_length=10),
        ),
    ]
