# Generated by Django 5.2.10 on 2026-05-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0051_alter_wallettransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='refund_reference',
            field=models.CharField(blank=True, default='', help_text='Référence externe du versement de remboursement (GeniusPay).', max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_status',
            field=models.CharField(blank=True, default='', help_text="'' | processing | paid | failed | manual — état du remboursement client.", max_length=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='refund_paid_at',
            field=models.DateTimeField(blank=True, help_text='Set une fois le remboursement client effectivement viré (payout).', null=True),
        ),
    ]
