# Generated by Django 5.2.10 on 2026-05-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0052_reservation_refund_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='photos_prestataire',
            field=models.JSONField(blank=True, default=list, help_text='Photos du diagnostic ajoutées par le prestataire au devis'),
        ),
    ]
