# Generated by Django 5.2.10 on 2026-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0053_devis_photos_prestataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remise commerciale accordée au client (déduite du sous-total).', max_digits=12),
        ),
    ]
