# Generated by Django 5.2.10 on 2026-05-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0040_reservation_fidelite_awarded_and_more'),
        ('adminpanel', '0054_devis_remise'),
    ]

    operations = [
    ]
