# Generated by Django 5.2.10 on 2026-05-31 00:19

from django.db import migrations, models


def drop_catalogue_table(apps, schema_editor):
    # Compatible MySQL (local) ET PostgreSQL (Render) : la syntaxe des
    # identifiants diffère (backticks MySQL vs guillemets Postgres), et
    # Postgres exige CASCADE pour lever les contraintes FK dépendantes.
    table = "adminpanel_catalogueitem"
    with schema_editor.connection.cursor() as c:
        if schema_editor.connection.vendor == "postgresql":
            c.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')
        else:
            c.execute(f"DROP TABLE IF EXISTS `{table}`")


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0056_structured_address'),
    ]

    operations = [
        migrations.RunPython(drop_catalogue_table, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='catalogueitem',
                    name='category',
                ),
                migrations.RemoveField(
                    model_name='lignedevis',
                    name='catalogue_item',
                ),
                migrations.DeleteModel(
                    name='CatalogueItem',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='call',
                    name='adminpanel__caller__ff9961_idx',
                ),
                migrations.RemoveIndex(
                    model_name='call',
                    name='adminpanel__callee__c99209_idx',
                ),
                migrations.RemoveIndex(
                    model_name='call',
                    name='adminpanel__reserva_548efa_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='devis',
                    name='net_prestataire',
                ),
                migrations.RemoveField(
                    model_name='devis',
                    name='photos_prestataire',
                ),
                migrations.RemoveField(
                    model_name='devis',
                    name='remise',
                ),
                migrations.RemoveField(
                    model_name='dispute',
                    name='categorie',
                ),
                migrations.RemoveField(
                    model_name='dispute',
                    name='decided_at',
                ),
                migrations.RemoveField(
                    model_name='dispute',
                    name='decided_by',
                ),
                migrations.RemoveField(
                    model_name='dispute',
                    name='decision_note',
                ),
                migrations.RemoveField(
                    model_name='dispute',
                    name='photos_client',
                ),
                migrations.RemoveField(
                    model_name='dispute',
                    name='photos_prestataire',
                ),
                migrations.RemoveField(
                    model_name='dispute',
                    name='prestataire_response',
                ),
                migrations.RemoveField(
                    model_name='dispute',
                    name='prestataire_response_at',
                ),
                migrations.RemoveField(
                    model_name='lignedevis',
                    name='marque',
                ),
                migrations.RemoveField(
                    model_name='lignedevis',
                    name='unite',
                ),
                migrations.RemoveField(
                    model_name='message',
                    name='kind',
                ),
                migrations.RemoveField(
                    model_name='message',
                    name='payload_json',
                ),
                migrations.RemoveField(
                    model_name='platformrevenue',
                    name='refunded_at',
                ),
                migrations.RemoveField(
                    model_name='provider',
                    name='has_used_premium_trial',
                ),
                migrations.RemoveField(
                    model_name='provider',
                    name='is_premium_annual',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='cancellation_by',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='cancellation_motif',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='cancellation_stage',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='cancelled_at',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='client_journal_note',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='client_journal_updated_at',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='client_photos_apres',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='client_photos_avant',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='created_at',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='funds_released_at',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='refund_owed_fcfa',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='refund_paid_at',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='refund_reference',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='refund_status',
                ),
                migrations.RemoveField(
                    model_name='reservation',
                    name='updated_at',
                ),
                migrations.RemoveField(
                    model_name='userprofile',
                    name='phone_verified',
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-id'], 'verbose_name': 'Appel', 'verbose_name_plural': 'Appels'},
        ),
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('RINGING', 'Sonne'), ('ANSWERED', 'Décroché'), ('REJECTED', 'Refusé'), ('ENDED', 'Terminé'), ('MISSED', 'Manqué')], default='RINGING', max_length=12),
        ),
        migrations.AlterField(
            model_name='devis',
            name='commission_montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devis',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devis',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='motif',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission en francs CFA', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué')], default='success', max_length=10),
        ),
    ]
