# Generated by Django 5.2.10 on 2026-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0057_remove_catalogueitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_journal_note',
            field=models.TextField(blank=True, default='', help_text="Commentaire libre du client à la fin de l'intervention"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_journal_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_photos_apres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_photos_avant',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
