# Generated by Django 5.2.10 on 2026-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0058_client_journal_fields_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='net_prestataire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
