# Generated by Django 5.2.10 on 2026-06-02 12:18
# Rendu idempotent pour les bases neuves (PostgreSQL/Render) : voir _compat.py.

from django.db import migrations, models

from ._compat import add_missing


def _forward(apps, schema_editor):
    add_missing(apps, schema_editor, "devis", [
        ("net_prestataire", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0058_client_journal_fields_fix'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_forward, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='devis',
                    name='net_prestataire',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
        ),
    ]
