# Generated by Django 5.2.10 on 2026-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0059_add_devis_net_prestataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address_is_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
