# Generated by Django 5.2.10 on 2026-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0060_address_is_approximate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de création du paiement', null=True),
        ),
    ]
