# Generated by Django 5.2.10 on 2026-06-04 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0062_payment_created_at_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='categorie',
            field=models.CharField(choices=[('travail_non_fait', 'Travail non réalisé'), ('travail_bacle', 'Travail bâclé / mal fait'), ('presta_absent', 'Prestataire absent / pas venu'), ('retard', 'Retard important'), ('prix_non_conforme', 'Prix non conforme au devis'), ('degats', 'Dégâts causés'), ('comportement', 'Comportement inapproprié'), ('autre', 'Autre')], db_index=True, default='autre', max_length=32),
        ),
        migrations.AddField(
            model_name='dispute',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='decision_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='photos_client',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dispute',
            name='photos_prestataire',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dispute',
            name='prestataire_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='prestataire_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='funds_released_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de libération escrow. Null = fonds encore bloqués. Set après client_confirme_prestation_at via EscrowService.release_funds.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_owed_fcfa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant que la plateforme doit rembourser au client (en attente admin)', max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_paid_at',
            field=models.DateTimeField(blank=True, help_text="Set par l'admin une fois le remboursement effectivement viré", null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_reference',
            field=models.CharField(blank=True, default='', help_text='Référence externe du versement de remboursement (GeniusPay).', max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_status',
            field=models.CharField(blank=True, default='', help_text="'' | processing | paid | failed | manual — état du remboursement client.", max_length=12),
        ),
    ]
