# Generated by Django 5.2.10 on 2026-06-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0063_dispute_categorie_dispute_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('USER', 'Message utilisateur'), ('DEVIS_CARD', 'Carte devis ancrée'), ('SYSTEM', 'Événement système')], db_index=True, default='USER', help_text='USER = message libre. DEVIS_CARD = devis figé ancré au fil. SYSTEM = événement (démarrage/fin/paiement).', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='payload_json',
            field=models.JSONField(blank=True, help_text='Données structurées pour les messages DEVIS_CARD/SYSTEM (montants, références, statuts…).', null=True),
        ),
    ]
