# Generated by Django 5.2.10 on 2026-06-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0064_message_kind_message_payload_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='photos_prestataire',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='devis',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remise commerciale accordée au client (déduite du sous-total).', max_digits=12),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='marque',
            field=models.CharField(blank=True, default='', help_text='Marque/référence matériau (optionnel, vue Kanban)', max_length=80),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(blank=True, default='', help_text='Unité (u, m, m², m³, ml, kg, h, jour, forfait…) — affichage UI', max_length=16),
        ),
    ]
