# Generated by Django 5.2.10 on 2026-06-04 00:57
# Rendu idempotent pour les bases neuves (PostgreSQL/Render) : voir _compat.py.

from django.db import migrations, models

from ._compat import add_missing


def _forward(apps, schema_editor):
    add_missing(apps, schema_editor, "devis", [
        ("photos_prestataire", models.JSONField(blank=True, default=list)),
        ("remise", models.DecimalField(decimal_places=2, default=0, help_text='Remise commerciale accordée au client (déduite du sous-total).', max_digits=12)),
    ])
    add_missing(apps, schema_editor, "lignedevis", [
        ("marque", models.CharField(blank=True, default='', help_text='Marque/référence matériau (optionnel, vue Kanban)', max_length=80)),
        ("unite", models.CharField(blank=True, default='', help_text='Unité (u, m, m², m³, ml, kg, h, jour, forfait…) — affichage UI', max_length=16)),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0064_message_kind_message_payload_json'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_forward, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='devis',
                    name='photos_prestataire',
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AddField(
                    model_name='devis',
                    name='remise',
                    field=models.DecimalField(decimal_places=2, default=0, help_text='Remise commerciale accordée au client (déduite du sous-total).', max_digits=12),
                ),
                migrations.AddField(
                    model_name='lignedevis',
                    name='marque',
                    field=models.CharField(blank=True, default='', help_text='Marque/référence matériau (optionnel, vue Kanban)', max_length=80),
                ),
                migrations.AddField(
                    model_name='lignedevis',
                    name='unite',
                    field=models.CharField(blank=True, default='', help_text='Unité (u, m, m², m³, ml, kg, h, jour, forfait…) — affichage UI', max_length=16),
                ),
            ],
        ),
    ]
