# Generated by Django 5.2.10 on 2026-06-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0065_devis_photos_prestataire_devis_remise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, upload_to='babifix_chat_audio/'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.PositiveIntegerField(default=0, help_text='Durée de la note vocale en secondes (affichage UI).'),
        ),
    ]
