# Generated by Django 5.2.10 on 2026-06-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0066_message_audio_message_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='kyc_documents_purged_at',
            field=models.DateTimeField(blank=True, help_text="Date de suppression des images d'identité (minimisation des données).", null=True),
        ),
    ]
