# Generated by Django 5.2.10 on 2026-06-04 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0067_provider_kyc_documents_purged_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nom du lieu : Maison, Bureau, Chez maman…', max_length=60)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address_label', models.CharField(blank=True, default='', max_length=255)),
                ('address_repere', models.CharField(blank=True, default='', help_text='Repère textuel : « à côté de la pharmacie X »', max_length=300)),
                ('is_default', models.BooleanField(default=False, help_text='Adresse proposée en premier (domicile principal).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babifix_saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='adminpanel__user_id_3710f5_idx')],
            },
        ),
    ]
