# Generated by Django 5.2.10 on 2026-06-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0068_clientsavedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='wallet_last_operator',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='wallet_last_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='wallet_operator_2',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('wave', 'Wave'), ('moov', 'Moov Money')], default='', help_text='Opérateur natif du 2e numéro', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='wallet_phone_2',
            field=models.CharField(blank=True, default='', help_text='2e numéro Mobile Money pour les retraits (secours)', max_length=20),
        ),
    ]
