# Generated by Django 5.2.10 on 2026-06-09 08:44

from django.db import migrations, models


def _backfill_app(apps, schema_editor):
    """Initialise app='pro' pour les jetons des comptes prestataires."""
    DeviceToken = apps.get_model('adminpanel', 'DeviceToken')
    UserProfile = apps.get_model('adminpanel', 'UserProfile')
    presta_ids = set(
        UserProfile.objects.filter(role='prestataire').values_list('user_id', flat=True)
    )
    if presta_ids:
        DeviceToken.objects.filter(user_id__in=presta_ids).update(app='pro')


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0069_provider_wallet_last_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='app',
            field=models.CharField(choices=[('client', 'Application Client (BABIFIX)'), ('pro', 'Application Prestataire (BABIFIX PRO)')], db_index=True, default='client', max_length=12),
        ),
        migrations.RunPython(_backfill_app, _noop),
    ]
