# Generated by Django 5.2.10 on 2026-06-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0072_seed_provider_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='refus_motif',
            field=models.TextField(blank=True, default=''),
        ),
    ]
