# Generated by Django 5.2.10 on 2026-06-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0073_devis_refus_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True, default='', help_text="URL de la photo de profil de l'utilisateur"),
        ),
    ]
