# Generated by Django 5.2.10 on 2026-06-15 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0075_reservation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetierPropose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('nom_normalise', models.CharField(db_index=True, max_length=120, unique=True)),
                ('emails', models.JSONField(blank=True, default=list, help_text='Emails des personnes intéressées (sert au comptage + notification)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('disponible', 'Disponible')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disponible_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Métier proposé',
                'verbose_name_plural': 'Métiers proposés',
                'ordering': ['-created_at'],
            },
        ),
    ]
