# Generated by Django 5.2.10 on 2026-06-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0076_metierpropose'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_premium_annual',
            field=models.BooleanField(default=False, help_text='Abonnement souscrit en formule annuelle (sinon mensuelle)'),
        ),
        migrations.AddField(
            model_name='provider',
            name='premium_trial_used',
            field=models.BooleanField(default=False, help_text="L'essai gratuit premium (7 jours) a déjà été utilisé"),
        ),
    ]
