# Generated by Django 5.2.10 on 2026-06-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0077_provider_is_premium_annual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='intervention_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
