# Generated by Django 5.2.10 on 2026-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0078_reservation_intervention_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
