# Generated by Django 5.2.10 on 2026-06-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0079_reservation_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
