# Generated by Django 5.2.10 on 2026-07-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0080_reservation_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='audio_probleme',
            field=models.CharField(blank=True, default='', help_text="URL d'une note vocale décrivant le besoin (facultatif)", max_length=500),
        ),
        migrations.AddField(
            model_name='reservation',
            name='demande_type',
            field=models.CharField(blank=True, choices=[('panne', 'Panne / réparation'), ('maintenance', 'Maintenance / entretien'), ('renovation', 'Réaménagement / rénovation'), ('installation', 'Installation / pose'), ('conseil', 'Devis / conseil'), ('autre', 'Autre')], default='', help_text='Nature de la demande (panne, maintenance, rénovation, pose...)', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(blank=True, default='', help_text='Unité (u, m, m², m³, ml, kg, h, jour, forfait…) : affichage UI', max_length=16),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Aligne sur statut Valide : visible apps client'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_certified',
            field=models.BooleanField(default=False, help_text="Badge 'Prestataire Certifie' : validation apres review admin"),
        ),
        migrations.AlterField(
            model_name='provider',
            name='photo_portrait_url',
            field=models.TextField(blank=True, default='', help_text='Photo de profil (URL) : visible après validation admin'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='portfolio_photos',
            field=models.JSONField(blank=True, default=list, help_text='Liste de {photo, caption, added_at} : max 12 entrées'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_propose',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix proposé par le client (optionnel : si différent du tarif catalogue)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='refund_status',
            field=models.CharField(blank=True, default='', help_text="'' | processing | paid | failed | manual : état du remboursement client.", max_length=12),
        ),
    ]
