# Generated by Django 5.2.10 on 2026-07-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0081_reservation_audio_probleme_reservation_demande_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='profil_devis',
            field=models.CharField(choices=[('STANDARD', 'Standard (photos + description)'), ('SURFACE', 'Surface / m² (peinture, carrelage)'), ('FORFAIT', 'Forfait / quantités (ménage, jardinage)'), ('DIAGNOSTIC', 'Diagnostic (plomberie, élec, clim)')], db_index=True, default='STANDARD', help_text='Profil de devis : oriente les questions posées au client. STANDARD = formulaire actuel inchangé.', max_length=16),
        ),
        migrations.AddField(
            model_name='category',
            name='template_exigences',
            field=models.JSONField(blank=True, default=list, help_text='Questions dynamiques (liste JSON) propres à la catégorie. Vide = formulaire actuel.'),
        ),
    ]
