# Generated by Django 5.2.10 on 2026-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0082_category_profil_devis_category_template_exigences'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reponses_exigences',
            field=models.JSONField(blank=True, default=dict, help_text='Réponses du client aux questions dynamiques de la catégorie (clé → valeur).'),
        ),
    ]
