# Generated by Django 5.2.10 on 2026-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0084_seed_category_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='est_estimation',
            field=models.BooleanField(default=False, help_text='True = estimation indicative (fourchette, non payable) ; False = devis ferme.'),
        ),
        migrations.AddField(
            model_name='devis',
            name='prix_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='devis',
            name='prix_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
