# Generated by Django 5.2.10 on 2026-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0085_devis_est_estimation_devis_prix_max_devis_prix_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='caution_deduite',
            field=models.BooleanField(default=False, help_text='La caution a été déduite du prix final (devis accepté).'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='caution_montant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la caution de visite (0 = pas de visite payante).', max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='caution_motif',
            field=models.CharField(blank=True, default='', help_text='Raison de la visite de diagnostic (affichée au client).', max_length=300),
        ),
        migrations.AddField(
            model_name='reservation',
            name='caution_payee',
            field=models.BooleanField(default=False, help_text='La caution de visite a été réglée par le client.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmee', 'Confirmee'), ('En cours', 'En cours'), ('En attente client', 'En attente client'), ('Terminee', 'Terminee'), ('Annulee', 'Annulee'), ('DEMANDE_ENVOYEE', 'Demande envoyée'), ('DEVIS_EN_COURS', 'Devis en cours'), ('VISITE_DIAGNOSTIC', 'Visite de diagnostic'), ('DEVIS_ENVOYE', 'Devis envoyé'), ('DEVIS_ACCEPTE', 'Devis accepté'), ('INTERVENTION_EN_COURS', 'Intervention en cours')], default='DEMANDE_ENVOYEE', max_length=30),
        ),
    ]
