# Generated by Django 5.2.10 on 2026-07-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0086_reservation_caution_deduite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='caution_remboursee',
            field=models.BooleanField(default=False, help_text='La caution a été remboursée au client (annulation avant visite).'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visite_effectuee',
            field=models.BooleanField(default=False, help_text='Le prestataire a effectué la visite de diagnostic.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visite_effectuee_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
