# Generated by Django 5.2.10 on 2026-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0087_reservation_caution_remboursee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='fiabilite_score',
            field=models.PositiveSmallIntegerField(default=100, help_text='Score de fiabilité 0–100 (indicatif). 100 = neutre/parfait.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='annulation_suspecte',
            field=models.BooleanField(default=False, help_text='Annulation flaggée comme suspecte (anti-désintermédiation).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fiabilite_score',
            field=models.PositiveSmallIntegerField(default=100, help_text='Score de fiabilité client 0–100 (indicatif). 100 = neutre.'),
        ),
    ]
