# Generated by Django 5.2.10 on 2026-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0088_provider_fiabilite_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caution_commission_pct', models.PositiveSmallIntegerField(default=12, help_text='Commission BABIFIX sur la caution de visite (%). Défaut 12.')),
                ('fiabilite_gating_actif', models.BooleanField(default=False, help_text='Si activé, un score de fiabilité bas a des conséquences (prestataire déprioritisé, client en prépaiement).')),
                ('fiabilite_seuil', models.PositiveSmallIntegerField(default=40, help_text="Sous ce score, les conséquences s'appliquent (si gating actif).")),
                ('delta_completion_presta', models.IntegerField(default=2)),
                ('delta_completion_client', models.IntegerField(default=1)),
                ('delta_client_annulation_suspecte', models.IntegerField(default=-8)),
                ('delta_client_annulation_tardive', models.IntegerField(default=-4)),
                ('delta_presta_noshow', models.IntegerField(default=-12)),
                ('delta_presta_annulation_tardive', models.IntegerField(default=-8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration plateforme',
                'verbose_name_plural': 'Configuration plateforme',
            },
        ),
    ]
