# Generated by Django 5.2.10 on 2026-07-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0089_platformconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrevenue',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_motif',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_stage',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
