# Generated by Django 5.2.10 on 2026-07-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0090_platformrevenue_refunded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='delta_presta_visite_suspecte',
            field=models.IntegerField(default=-10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='frais_mise_en_relation_fcfa',
            field=models.PositiveIntegerField(default=500, help_text='Frais fixe de mise en relation payé par le client à la visite (FCFA). Défaut 500.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='radar_visite_sans_devis_jours',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visite_suspecte',
            field=models.BooleanField(db_index=True, default=False, help_text='Radar : caution payée mais aucun devis → visite jugée suspecte.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visite_suspecte_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visite_suspecte_motif',
            field=models.CharField(blank=True, default='', help_text="Détail du signalement radar (pour l'admin).", max_length=255),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='caution_commission_pct',
            field=models.PositiveSmallIntegerField(default=12, help_text='[Déprécié] Commission BABIFIX sur la caution de visite (%).'),
        ),
    ]
