# Generated by Django 5.2.10 on 2026-07-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0091_platformconfig_delta_presta_visite_suspecte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='auto_suspension_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='suspension_score_seuil',
            field=models.PositiveSmallIntegerField(default=20, help_text='Score de fiabilité sous lequel le compte est suspendu automatiquement.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='suspension_visites_suspectes',
            field=models.PositiveSmallIntegerField(default=3, help_text='Nombre de visites suspectes qui déclenche la suspension automatique.'),
        ),
    ]
