# Generated by Django 5.2.10 on 2026-07-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0092_platformconfig_auto_suspension_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='remise_fidelite',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remise fidélité (crédit) appliquée, absorbée par BABIFIX.', max_digits=12),
        ),
    ]
