# Generated by Django 5.2.10 on 2026-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0093_reservation_remise_fidelite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='video_probleme',
            field=models.CharField(blank=True, default='', help_text="URL d'une courte vidéo montrant le problème (facultatif)", max_length=500),
        ),
    ]
